# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campusonline", "0048_finalthesis"),
        ("attendance", "0015_auto_20190306_1647"),
    ]

    operations = [
        migrations.RemoveField(model_name="entry", name="room"),
        migrations.RemoveField(model_name="entry", name="status"),
        migrations.AddField(
            model_name="campusonlineentry",
            name="room",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="campusonline.Room",
            ),
        ),
        migrations.AlterField(
            model_name="campusonlineentry",
            name="holding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="attendance.CampusOnlineHolding",
            ),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="behaviour",
            field=outpost.django.base.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "outpost.django.attendance.plugins.StatisticsTerminalBehaviour",
                            "Statistiken",
                        ),
                        (
                            "outpost.django.attendance.plugins.DebugTerminalBehaviour",
                            "Debugger",
                        ),
                        (
                            "outpost.django.attendance.plugins.CampusOnlineTerminalBehaviour",
                            "CAMPUSonline",
                        ),
                    ],
                    max_length=256,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
