# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("attendance", "0016_auto_20190625_1700")]

    operations = [
        migrations.AlterField(
            model_name="campusonlineentry",
            name="incoming",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campusonlineentry",
                to="attendance.Entry",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="attendance",
                to="campusonline.Student",
            ),
        ),
    ]
