# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-18 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("campusonline", "0053_external"),
        ("attendance", "0021_auto_20200915_1006"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualCampusOnlineEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned", models.DateTimeField(blank=True, null=True)),
                ("ended", models.DateTimeField(blank=True, null=True)),
                ("state", django_fsm.FSMField(default="assigned", max_length=50)),
                (
                    "holding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_entries",
                        to="attendance.CampusOnlineHolding",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="campusonline.Room",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="campusonline.Student",
                    ),
                ),
            ],
            options={
                "ordering": ("assigned", "ended"),
                "permissions": (
                    ("view_manualcampusonlineentry", "View manual CAMPUSonline Entry"),
                ),
            },
        )
    ]
