# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.fields


class Migration(migrations.Migration):

    dependencies = [("attendance", "0022_manualcampusonlineentry")]

    operations = [
        migrations.AlterField(
            model_name="manualcampusonlineentry",
            name="holding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_entries",
                to="attendance.CampusOnlineHolding",
            ),
        ),
        migrations.AlterField(
            model_name="manualcampusonlineentry",
            name="room",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="campusonline.Room",
            ),
        ),
        migrations.AlterField(
            model_name="manualcampusonlineentry",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="campusonline.Student",
            ),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="behaviour",
            field=outpost.django.base.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "outpost.django.attendance.plugins.StatisticsTerminalBehaviour",
                            "Statistiken",
                        ),
                        (
                            "outpost.django.attendance.plugins.CampusOnlineTerminalBehaviour",
                            "CAMPUSonline",
                        ),
                        (
                            "outpost.django.attendance.plugins.DebugTerminalBehaviour",
                            "Debugger",
                        ),
                    ],
                    max_length=256,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
