# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-01 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import outpost.django.base.fields


class Migration(migrations.Migration):

    dependencies = [("attendance", "0023_auto_20201120_1530")]

    operations = [
        migrations.AddField(
            model_name="campusonlineentry",
            name="accredited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manualcampusonlineentry",
            name="accredited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="behaviour",
            field=outpost.django.base.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "outpost.django.attendance.plugins.DebugTerminalBehaviour",
                            "Debugger",
                        ),
                        (
                            "outpost.django.attendance.plugins.CampusOnlineTerminalBehaviour",
                            "CAMPUSonline",
                        ),
                        (
                            "outpost.django.attendance.plugins.StatisticsTerminalBehaviour",
                            "Statistiken",
                        ),
                    ],
                    max_length=256,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
