# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import outpost.django.base.fields


class Migration(migrations.Migration):

    dependencies = [("attendance", "0024_auto_20201201_1431")]

    operations = [
        migrations.AlterField(
            model_name="manualcampusonlineentry",
            name="assigned",
            field=models.DateTimeField(auto_now_add=True, null=True),
        )
    ]
