# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.fields


class Migration(migrations.Migration):

    dependencies = [("attendance", "0025_auto_20210120_1413")]

    operations = [
        migrations.AlterField(
            model_name="campusonlineholding",
            name="course_group_term",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="campus_online_holdings",
                to="campusonline.CourseGroupTerm",
            ),
        ),
        migrations.AlterField(
            model_name="campusonlineholding",
            name="lecturer",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="campus_online_holdings",
                to="campusonline.Person",
            ),
        ),
        migrations.AlterField(
            model_name="campusonlineholding",
            name="room",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="campus_online_holdings",
                to="campusonline.Room",
            ),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="behaviour",
            field=outpost.django.base.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "outpost.django.attendance.plugins.DebugTerminalBehaviour",
                            "Debugger",
                        ),
                        (
                            "outpost.django.attendance.plugins.StatisticsTerminalBehaviour",
                            "Statistiken",
                        ),
                        (
                            "outpost.django.attendance.plugins.CampusOnlineTerminalBehaviour",
                            "CAMPUSonline",
                        ),
                    ],
                    max_length=256,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
