# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import outpost.django.base.fields
import outpost.django.base.utils
import outpost.django.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0026_auto_20210201_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminal",
            name="screen",
            field=models.ImageField(
                null=True,
                upload_to=outpost.django.base.utils.Uuid4Upload,
                validators=[
                    outpost.django.base.validators.FileValidator(
                        mimetypes=["image/png"]
                    )
                ],
            ),
        ),
    ]
