# Generated by Django 2.2.28 on 2023-09-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0029_auto_20211013_2123"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campusonlineentry",
            options={
                "ordering": ("incoming__created", "assigned", "ended"),
                "permissions": (),
            },
        ),
        migrations.AlterModelOptions(
            name="campusonlineholding",
            options={"get_latest_by": "initiated", "permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="entry",
            options={"get_latest_by": "created", "permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="manualcampusonlineentry",
            options={"ordering": ("assigned", "ended"), "permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="statistics",
            options={"ordering": ("id",), "permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="terminal",
            options={"ordering": ("id",), "permissions": ()},
        ),
    ]
