# Generated by Django 4.2.28 on 2026-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0030_auto_20230919_1113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminal",
            name="config",
            field=models.JSONField(null=True),
        ),
    ]
